name: CI

on: 
  push:
    tags:
    - 'v*'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: zip
      run: 7z a -tzip -mx=9 $Env:GITHUB_WORKSPACE\Sharer.zip $Env:GITHUB_WORKSPACE\library.properties $Env:GITHUB_WORKSPACE\src $Env:GITHUB_WORKSPACE\examples
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "Sharer.zip"
        bodyFile: "Instructions.md"
        token: ${{ secrets.GITHUB_TOKEN }}
